services:
   web:
     build: .
       #command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb -p 3000  
     volumes:
       - .:/myapp
       - gem_cache:/usr/local/bundle/gems
       - node_modules:/myapp/node_modules
     env_file: .env 
     ports:
       - "3000:3000"
         #environment:
         #  RAILS_ENV:  production
         #  RACK_ENV:  production
     container_name: "ruby"
   web-nginx:
     build:
       context: .
       dockerfile: dockerfile.nginx
     ports:
       - "80:80"
     depends_on:
       - web
       - database
     container_name: "nginx"
       # volumes:
       #- ./default.conf:/etc/nginx/conf.d/default.conf                
   database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initial-setup.sh:/initial-setup-initdb.d/initial-setup.sh
volumes:
  gem_cache:
  db_data:
  node_modules: 
