services:
   web:
     build: .
       #command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb -p 3000  
     volumes:
       - .:/myapp
     ports:
       - "3000:3000"
         #environment:
         #DB_USER: postgres
         # DB_NAME: myapp
         #  DB_PASSWORD: admin321
         #  DB_HOST: database-1.cakidksrmeek.ap-south-1.rds.amazonaws.com
         #  DB_PORT: 5432
         #  RAILS_ENV:  production
         #  RACK_ENV:  production
     container_name: "ruby"
   web-nginx:
     build:
       context: .
       dockerfile: dockerfile.nginx
     ports:
       - "80:80"
     depends_on:
       - web
     container_name: "nginx"
       # volumes:
       #- ./default.conf:/etc/nginx/conf.d/default.conf                 